//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int acc_id { get; set; }
        public Nullable<int> act_code { get; set; }
        public string acc_name { get; set; }
        public string acc_pass { get; set; }
        public string Roles { get; set; }
    }
}
