//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Info
    {
        public int id { get; set; }
        public Nullable<int> acc_id { get; set; }
        public Nullable<int> acc_zipcode { get; set; }
        public string acc_city { get; set; }
    }
}
