//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int cus_id { get; set; }
        public string cus_fn { get; set; }
        public string cus_lf { get; set; }
        public string cus_mail { get; set; }
        public Nullable<int> cus_phone { get; set; }
    }
}
