//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {


        public int cus_id { get; set; }
        [Required]
        [DisplayName("Fornavn")]
        public string cus_fn { get; set; }
        [Required]
        [DisplayName("Efternavn")]
        public string cus_lf { get; set; }
        [Required]
        [DisplayName("E-mail")]
        public string cus_mail { get; set; }
        [Required]
        [DisplayName("Telefon")]
        public Nullable<int> cus_phone { get; set; }
    }
}
